@ stub ClosePackageInfo
@ stub FindPackagesByPackageFamily
@ stub FormatApplicationUserModelId
@ stub GetApplicationUserModelId
@ stub GetApplicationUserModelIdFromToken
@ stub GetCurrentApplicationUserModelId
@ stdcall GetCurrentPackageFamilyName(ptr ptr) kernel32.GetCurrentPackageFamilyName
@ stub GetCurrentPackageFullName
@ stdcall GetCurrentPackageId(ptr ptr) kernel32.GetCurrentPackageId
@ stub GetCurrentPackageInfo
@ stub GetCurrentPackagePath
@ stub GetPackageApplicationIds
@ stub GetPackageFamilyName
@ stub GetPackageFamilyNameFromToken
@ stub GetPackageFullName
@ stub GetPackageFullNameFromToken
@ stub GetPackageId
@ stub GetPackageInfo
@ stub GetPackagePath
@ stub GetPackagePathByFullName
@ stub GetPackagesByPackageFamily
@ stub GetStagedPackageOrigin
@ stub GetStagedPackagePathByFullName
@ stub OpenPackageInfoByFullName
@ stub OpenPackageInfoByFullNameForUser
@ stub PackageFamilyNameFromFullName
@ stub PackageFamilyNameFromId
@ stub PackageFullNameFromId
@ stub PackageIdFromFullName
@ stub PackageNameAndPublisherIdFromFamilyName
@ stub ParseApplicationUserModelId
@ stub VerifyApplicationUserModelId
@ stub VerifyPackageFamilyName
@ stub VerifyPackageFullName
@ stub VerifyPackageId
@ stub VerifyPackageRelativeApplicationId
